build:
    environment:
        php:
            version: 7.4

    nodes:
      coverage:
        tests:
          override:
            - command: XDEBUG_MODE=coverage vendor/bin/phpunit --testdox --verbose
              coverage:
                file: coverage-report/coverage.xml
                format: clover
